# Generated by Django 6.1.1 on 2026-09-22 04:51

import accounts.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('posts', '0003_post_allow_comments_post_feeling_post_is_pinned_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.banner_upload_path),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_deactivated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='pinned_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='posts.post'),
        ),
        migrations.AddField(
            model_name='profile',
            name='who_can_comment',
            field=models.CharField(choices=[('everyone', 'Everyone'), ('followers', 'Followers Only')], default='everyone', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='who_can_message',
            field=models.CharField(choices=[('everyone', 'Everyone'), ('followers', 'Followers Only'), ('nobody', 'Nobody')], default='everyone', max_length=20),
        ),
    ]
