# Generated by Django 6.1.1 on 2026-09-22 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('all', 'All'), ('social', 'Social'), ('mentions', 'Mentions'), ('messages', 'Messages')], default='social', max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='action_type',
            field=models.CharField(choices=[('like', 'liked your post'), ('reaction', 'reacted to your post'), ('comment', 'commented on your post'), ('reply', 'replied to your comment'), ('follow', 'started following you'), ('follow_request', 'requested to follow you'), ('follow_accept', 'accepted your follow request'), ('mention', 'mentioned you in a post'), ('repost', 'shared your post'), ('story_view', 'viewed your moment')], max_length=20),
        ),
    ]
